repos:
  # General checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # - name: Prevent committing to main
      #   id: no-commit-to-branch
      #   args: [--branch, main]
      - name: Make sure files end with a newline character
        id: end-of-file-fixer
      - name: Remove trailing whitespace
        id: trailing-whitespace
      - name: Check for files that would conflict on case-insensitive filesystem
        id: check-case-conflict
      - name: Check for merge conflicts
        id: check-merge-conflict
      - name: Check executable files have a shebang
        id: check-executables-have-shebangs
      - name: Check scripts with a shebang are executable
        id: check-shebang-scripts-are-executable
      - name: Don't allow adding large files
        id: check-added-large-files

  # Python
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - name: Validate Python
        id: check-ast
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - name: Format Python files
        id: ruff-format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - name: Lint Python files
        id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.327
    hooks:
      - name: Type-check Python files
        id: pyright
  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.0
    hooks:
      - name: Check Poetry configuration
        id: poetry-check
      - name: Run Poetry lock
        id: poetry-lock
        args: [--no-update]

  # YAML
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - name: Validate YAML
        id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - name: Format YAML files
        id: prettier
        types: [yaml]

  # TOML
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - name: Validate TOML
        id: check-toml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - name: Format TOML files
        id: prettier
        types: [toml]

  # Markdown
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.10.0
    hooks:
      - name: Lint markdown files
        id: markdownlint-cli2
        args: [--config, .markdownlint.jsonc]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - name: Format markdown files
        id: prettier
        types: [markdown]

  # GitHub Actions
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.26.3
    hooks:
      - name: Validate GitHub Actions workflow files
        id: check-github-workflows

  # Pre-commit
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.26.3
    hooks:
      - name: Validate Pre-commit config
        id: check-jsonschema
        files: ^.*\.pre-commit-config.yaml$
        args:
          [
            "--schemafile",
            "https://json.schemastore.org/pre-commit-config.json",
          ]

  # Nix
  - repo: https://github.com/kamadorueda/alejandra
    rev: 3.0.0
    hooks:
      - name: Format Nix files
        id: alejandra

